INSERT INTO DBUSER.RESERVIERUNGSAUFSCHLAG(VON, BIS, WAGONTYP_BEZEICHNUNG, KOSTEN)
VALUES(TO_DATE('1999', 'YYYY'), TO_DATE('2019', 'YYYY'), 'Bombardier Talent', 0.5);
INSERT INTO DBUSER.RESERVIERUNGSAUFSCHLAG(VON, BIS, WAGONTYP_BEZEICHNUNG, KOSTEN)
VALUES(TO_DATE('2019', 'YYYY'), TO_DATE('2021', 'YYYY'), 'Bombardier Talent', 0.75);
INSERT INTO DBUSER.RESERVIERUNGSAUFSCHLAG(VON, BIS, WAGONTYP_BEZEICHNUNG, KOSTEN)
VALUES(TO_DATE('2021', 'YYYY'), TO_DATE('2023', 'YYYY'), 'Bombardier Talent', 1);
INSERT INTO DBUSER.RESERVIERUNGSAUFSCHLAG(VON, BIS, WAGONTYP_BEZEICHNUNG, KOSTEN)
VALUES(TO_DATE('2023', 'YYYY'), TO_DATE('9999', 'YYYY'), 'Bombardier Talent', 2);