INSERT INTO DBUSER.KLASSE(ID, BEZEICHNUNG) VALUES(0, 'Economy Class');
INSERT INTO DBUSER.KLASSE(ID, BEZEICHNUNG) VALUES(1, 'First Class');
INSERT INTO DBUSER.KLASSE(ID, BEZEICHNUNG) VALUES(2, 'Business Class');