INSERT INTO DBUSER.DAUERTYP(ID, LANGE_BEZEICHNUNG) VALUES('24H', '24 Stunden Ticket');
INSERT INTO DBUSER.DAUERTYP(ID, LANGE_BEZEICHNUNG) VALUES('MO', 'Monatsticket');
INSERT INTO DBUSER.DAUERTYP(ID, LANGE_BEZEICHNUNG) VALUES('JA', 'Jahresticket');