INSERT INTO DBUSER.ZUGTYP(ID, NAME) VALUES('S', 'S-Bahn');
INSERT INTO DBUSER.ZUGTYP(ID, NAME) VALUES('REX', 'Regionalexpress');
INSERT INTO DBUSER.ZUGTYP(ID, NAME) VALUES('EC', 'Eurocity');
INSERT INTO DBUSER.ZUGTYP(ID, NAME) VALUES('IC', 'Intercity');
INSERT INTO DBUSER.ZUGTYP(ID, NAME) VALUES('RJ', 'Railjet');