
INSERT INTO FAHRPLAN(NR, NAME, VON_DATUM, BIS_DATUM, ZUG_ZUGNUMMER) VALUES(1, 'S3 von Salzburg nach Zell', TO_DATE('1999', 'YYYY'), TO_DATE('9999', 'YYYY'), 25769);

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1440', 'hh24mi'), TO_DATE('1442', 'hh24mi'), 1, 1, 2, 'Salzburg Liefering Bahnhof', 'Salzburg Taxham Europark Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1442', 'hh24mi'), TO_DATE('1444', 'hh24mi'), 1, 2, 1, 'Salzburg Taxham Europark Bahnhof', 'Salzburg Aiglhof Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1445', 'hh24mi'), TO_DATE('1446', 'hh24mi'), 1, 1, 1, 'Salzburg Aiglhof Bahnhof', 'Salzburg Mülln-Altstadt Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1446', 'hh24mi'), TO_DATE('1449', 'hh24mi'), 1, 1, 9, 'Salzburg Mülln-Altstadt Bahnhof', 'Salzburg Hbf');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1451', 'hh24mi'), TO_DATE('1454', 'hh24mi'), 1, 9, 2, 'Salzburg Hbf', 'Salzburg Sam Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1455', 'hh24mi'), TO_DATE('1456', 'hh24mi'), 1, 2, 2, 'Salzburg Sam Bahnhof', 'Salzburg Gnigl Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1456', 'hh24mi'), TO_DATE('1458', 'hh24mi'), 1, 2, 2, 'Salzburg Gnigl Bahnhof', 'Salzburg Parsch Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1459', 'hh24mi'), TO_DATE('1500', 'hh24mi'), 1, 2, 1, 'Salzburg Parsch Bahnhof', 'Salzburg Aigen Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1501', 'hh24mi'), TO_DATE('1503', 'hh24mi'), 1, 1, 2, 'Salzburg Aigen Bahnhof', 'Salzburg Süd Bahnhst');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1503', 'hh24mi'), TO_DATE('1504', 'hh24mi'), 1, 2, 2, 'Salzburg Süd Bahnhst', 'Elsbethen Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1505', 'hh24mi'), TO_DATE('1508', 'hh24mi'), 1, 2, 2, 'Elsbethen Bahnhof', 'Puch b.Hallein Urstein Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1508', 'hh24mi'), TO_DATE('1510', 'hh24mi'), 1, 2, 2, 'Puch b.Hallein Urstein Bahnhof', 'Puch b.Hallein Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1510', 'hh24mi'), TO_DATE('1512', 'hh24mi'), 1, 2, 2, 'Puch b.Hallein Bahnhof', 'Oberalm Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1512', 'hh24mi'), TO_DATE('1514', 'hh24mi'), 1, 2, 2, 'Oberalm Bahnhof', 'Hallein Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1515', 'hh24mi'), TO_DATE('1517', 'hh24mi'), 1, 2, 2, 'Hallein Bahnhof', 'Hallein Burgfried Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1517', 'hh24mi'), TO_DATE('1519', 'hh24mi'), 1, 2, 2, 'Hallein Burgfried Bahnhof', 'Bad Vigaun Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1519', 'hh24mi'), TO_DATE('1521', 'hh24mi'), 1, 2, 2, 'Bad Vigaun Bahnhof', 'Kuchl Garnei Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1521', 'hh24mi'), TO_DATE('1524', 'hh24mi'), 1, 2, 2, 'Kuchl Garnei Bahnhof', 'Kuchl Bahnhof');

INSERT INTO STRECKENABSCHNITT(ABFAHRTSZEIT, ANKUNFTSZEIT, FAHRPLAN_NR, ABFAHRT_BAHNSTEIG_NR, ANKUNFT_BAHNSTEIG_NR, ABFAHRT_BAHNHOF_NAME, ANKUNFT_BAHNHOF_NAME)
VALUES(TO_DATE('1525', 'hh24mi'), TO_DATE('1528', 'hh24mi'), 1, 2, 1, 'Kuchl Bahnhof', 'Golling-Abtenau Bahnhof');